version: '3'
services:

# Server service with Laravel 9 + nodejs + php8
  server_service:
    image: tangramor/nginx-php8-fpm
    environment:
      WEBROOT: '/var/www/public'
    ports:
      - '${APP_PORT:-80}:80'
    volumes:
      - './src:/var/www'
    networks:
      - sail
    depends_on:
      - mysql_service

# MySQL 8 Service
  mysql_service:
    image: 'mysql/mysql-server:8.0'
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
    volumes:
      - 'sail-mysql:/var/lib/mysql'
    networks:
      - sail

networks:
  sail:
    driver: bridge
volumes:
  sail-mysql:
    driver: local